FROM node:16-alpine AS builder

WORKDIR /app
COPY package*.json ./
ENV SKIP_POSTINSTALL=1
RUN npm install
COPY . .
RUN npm run build --prod

# Segunda etapa: usar http-server
FROM node:16-alpine
RUN npm install -g http-server

WORKDIR /app
COPY --from=builder /app/dist/ /app

EXPOSE 8080

CMD ["http-server", "-p", "8080"]